# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

job: cim
scenario: cim
mode: sync
num_episodes: 10
eval_schedule: 10
num_steps: -1
max_lag: 0
sync:
  rollout_type: distributed   # simple, distributed
  simple:
    parallelism: 1
    eval_parallelism: 1
  distributed:
    group: rollout
    num_workers: 4
    num_eval_workers: 1
    min_finished_workers: 3
    max_extra_recv_tries: 2
    extra_recv_timeout: 200
async:
  group: async
  num_actors: 3
policy_manager:
  type: distributed   # simple, distributed
  simple:
    parallel: false
  distributed:
    group: learn
    num_hosts: 2
data_parallel:
  enable: false
  num_workers: 2
  allocation_mode: by-policy  # by-policy, by-agent, by-experience
redis:
  host: redis-server
  port: 6379
